<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CavsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('cavs')->insert([

['ciudad_id' => '1','nombre' =>  'Cav Acacias'],
['ciudad_id' => '2','nombre' => 'Cav Aguachica'],
['ciudad_id' => '3','nombre' =>  'Cav Apartado'],
['ciudad_id' => '4','nombre' =>  'Cav Centro'],
['ciudad_id' => '4','nombre' =>  'Cav Portal Quindío'],
['ciudad_id' => '5','nombre' =>  'Cav Barrancabermeja'],
['ciudad_id' => '6','nombre' =>  'Cav Prado'],
['ciudad_id' => '6','nombre' =>  'Tienda Mall Plaza'],
['ciudad_id' => '6','nombre' =>  'Cav Metropolitano'],
['ciudad_id' => '6','nombre' =>  'Cav Parque Alegra'],
['ciudad_id' => '6','nombre' =>  'Cav Centro'],
['ciudad_id' => '7','nombre' =>  'Cav Puerta Del Norte'],
['ciudad_id' => '7','nombre' =>  'Tienda Plaza Fabricato'],
['ciudad_id' => '8','nombre' =>  'Cav Santafé'],
['ciudad_id' => '8','nombre' =>  'Cav Plaza Imperial'],
['ciudad_id' => '8','nombre' =>  'Cav Toberín'],
['ciudad_id' => '8','nombre' =>  'Cav Calle 140'],
['ciudad_id' => '8','nombre' =>  'Cav Niza'],
['ciudad_id' => '8','nombre' =>  'Tienda Colina'],
['ciudad_id' => '8','nombre' =>  'Cav Álamos'],
['ciudad_id' => '8','nombre' =>  'Cav Fontibón'],
['ciudad_id' => '8','nombre' =>  'Cav La Felicidad'],
['ciudad_id' => '8','nombre' =>  'Cav Unicentro'],
['ciudad_id' => '8','nombre' =>  'Tienda Titán Plaza'],
['ciudad_id' => '8','nombre' =>  'Tienda Portal 80'],
['ciudad_id' => '8','nombre' =>  'Cav Tienda Hayuelos'],
['ciudad_id' => '8','nombre' =>  'Cav Centro Mayor'],
['ciudad_id' => '8','nombre' =>  'Cav Restrepo'],
['ciudad_id' => '8','nombre' =>  'Cav Cra 7'],
['ciudad_id' => '8','nombre' =>  'Cav Chapinero'],
['ciudad_id' => '8','nombre' =>  'Cav Floresta'],
['ciudad_id' => '8','nombre' =>  'Cav Calle 84'],
['ciudad_id' => '8','nombre' =>  'Cav Mall Plaza NQS'],
['ciudad_id' => '8','nombre' =>  'Cav Plaza Claro'],
['ciudad_id' => '8','nombre' =>  'Tienda Gran Estación'],
['ciudad_id' => '8','nombre' =>  'Tienda Andino'],
['ciudad_id' => '8','nombre' =>  'Cav Kennedy'],
['ciudad_id' => '8','nombre' =>  'Cav Venecia'],
['ciudad_id' => '8','nombre' =>  'Cav Plaza de las Americas'],
['ciudad_id' => '8','nombre' =>  'Tienda Gran Plaza Bosa'],
['ciudad_id' => '8','nombre' =>  'Tienda Paseo Villa del Rio'],
['ciudad_id' => '8','nombre' =>  'Tienda Ensueño'],
['ciudad_id' => '9','nombre' =>  'Cav Cabecera'],
['ciudad_id' => '9','nombre' =>  'Cav Omnicentro'],
['ciudad_id' => '10','nombre' =>  'Cav Buenaventura'],
['ciudad_id' => '10','nombre' =>  'Tienda Malecón'],
['ciudad_id' => '11','nombre' =>  'Cav Chipichape'],
['ciudad_id' => '11','nombre' =>  'Cav la Estación'],
['ciudad_id' => '11','nombre' =>  'Cav Norte'],
['ciudad_id' => '11','nombre' =>  'Cav Palmetto'],
['ciudad_id' => '11','nombre' =>  'Cav Gran Comercio'],
['ciudad_id' => '11','nombre' =>  'Cav Sur'],
['ciudad_id' => '12','nombre' =>  'Cav Bocagrande'],
['ciudad_id' => '12','nombre' =>  'Cav Ejecutivos'],
['ciudad_id' => '12','nombre' =>  'Tienda Caribe Plaza'],
['ciudad_id' => '12','nombre' =>  'Tienda Mall plaza'],
['ciudad_id' => '13','nombre' =>  'Cav Cartago'],
['ciudad_id' => '14','nombre' =>  'Cav Caucasia'],
['ciudad_id' => '15','nombre' =>  'Cav Fontanar'],
['ciudad_id' => '15','nombre' =>  'Cav La Libertad'],
['ciudad_id' => '16','nombre' =>  'Cav Centro'],
['ciudad_id' => '16','nombre' =>  'Cav Av Gran Colombia'],
['ciudad_id' => '17','nombre' =>  'Cav Duitama'],
['ciudad_id' => '18','nombre' =>  'Tienda Viva'],
['ciudad_id' => '19','nombre' =>  'Cav Florencia'],
['ciudad_id' => '20','nombre' =>  'Cav La Florida'],
['ciudad_id' => '21','nombre' =>  'Cav Fusagasugá'],
['ciudad_id' => '22','nombre' =>  'Cav Girardot'],
['ciudad_id' => '23','nombre' =>  'Cav Centro'],
['ciudad_id' => '23','nombre' =>  'Cav Fontainebleau'],
['ciudad_id' => '24','nombre' =>  'Cav Ipiales'],
['ciudad_id' => '25','nombre' =>  'Cav Arrayanes'],
['ciudad_id' => '26','nombre' =>  'Cav La Dorada'],
['ciudad_id' => '27','nombre' =>  'Cav El Cable'],
['ciudad_id' => '27','nombre' =>  'Tienda Manizales'],
['ciudad_id' => '28','nombre' =>  'Cav Premium'],
['ciudad_id' => '28','nombre' =>  'Cav Molinos'],
['ciudad_id' => '28','nombre' =>  'Cav Av. Colombia'],
['ciudad_id' => '28','nombre' =>  'Tienda Arkadia'],
['ciudad_id' => '28','nombre' =>  'Tienda Santa Fé'],
['ciudad_id' => '29','nombre' =>  'Cav Alameda'],
['ciudad_id' => '30','nombre' =>  'Cav Mosquera'],
['ciudad_id' => '31','nombre' =>  'Cav Centro'],
['ciudad_id' => '31','nombre' =>  'Cav San Pedro'],
['ciudad_id' => '32','nombre' =>  'Cav Centro'],
['ciudad_id' => '33','nombre' =>  'Cav Pasto'],
['ciudad_id' => '33','nombre' =>  'Tienda Pasto'],
['ciudad_id' => '34','nombre' =>  'Cav Estación Central'],
['ciudad_id' => '34','nombre' =>  'Cav La Rebeca'],
['ciudad_id' => '34','nombre' =>  'Tienda Arboleda'],
['ciudad_id' => '35','nombre' =>  'Cav Campanario'],
['ciudad_id' => '35','nombre' =>  'Cav Plaza Colonial'],
['ciudad_id' => '36','nombre' =>  'Cav Quibdó'],
['ciudad_id' => '37','nombre' =>  'Cav Riohacha'],
['ciudad_id' => '38','nombre' =>  'Cav Rionegro'],
['ciudad_id' => '39','nombre' =>  'Tienda Mayorca'],
['ciudad_id' => '40','nombre' =>  'Cav San Andres'],
['ciudad_id' => '41','nombre' =>  'Cav Buenavista'],
['ciudad_id' => '41','nombre' =>  'Tienda Santa Marta'],
['ciudad_id' => '42','nombre' =>  'Cav Guacarí'],
['ciudad_id' => '43','nombre' =>  'Cav Mercurio II'],
['ciudad_id' => '43','nombre' =>  'Tienda Ventura'],
['ciudad_id' => '44','nombre' =>  'Cav Sogamoso'],
['ciudad_id' => '45','nombre' =>  'Cav Salesiano'],
['ciudad_id' => '46','nombre' =>  'Cav Tumaco'],
['ciudad_id' => '47','nombre' =>  'Cav Viva'],
['ciudad_id' => '48','nombre' =>  'Cav Guatapurí'],
['ciudad_id' => '48','nombre' =>  'Cav Mayales'],
['ciudad_id' => '49','nombre' =>  'Cav Oriente'],
['ciudad_id' => '49','nombre' =>  'Cav Villa Centro'],
['ciudad_id' => '50','nombre' =>  'Cav Yopal'],
['ciudad_id' => '51','nombre' =>  'Cav Zipaquirá']


        ]);
    }
}
